#Quiz 1：機器學習分類任務

Step 1：先取得資料

In [31]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = data.data
y = data.target

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (569, 30)
y shape: (569,)


Step 2：理解 X 和 y

In [32]:
X = data.data
y = data.target
X,y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

Step 3：看看兩個類別有多少筆

In [33]:
import numpy as np

unique, counts = np.unique(y, return_counts=True)

for label, count in zip(unique, counts):
    print(f"Class {label}: {count}")

Class 0: 212
Class 1: 357


Step 4：切 Training / Validation

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("y_train:", y_train.shape)
print("y_val:", y_val.shape)

X_train: (455, 30)
X_val: (114, 30)
y_train: (455,)
y_val: (114,)


Step 5： Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

Step 6：看看 Scaling 前後

In [36]:
print("Before scaling:")
print(X_train[:3, :3])

print("\nAfter scaling:")
print(X_train_scaled[:3, :3])

Before scaling:
[[ 10.32  16.35  65.31]
 [ 20.18  19.54 133.8 ]
 [ 10.66  15.15  67.49]]

After scaling:
[[-1.07200079 -0.6584246  -1.0880801 ]
 [ 1.74874285  0.06650173  1.75115682]
 [-0.97473376 -0.93112416 -0.99770871]]


Step 7 : 建立 Machine Learning Classification Model

In [37]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

Step 8 : 讓模型預測 Validation Dataset

In [38]:
y_prob = model.predict_proba(X_val_scaled)[:, 1]

for i, prob in enumerate(y_prob[:10]):
    print(f"第 {i+1} 筆：{prob:.6f}")

第 1 筆：0.000000
第 2 筆：0.999989
第 3 筆：0.006411
第 4 筆：0.535736
第 5 筆：0.000000
第 6 筆：0.992041
第 7 筆：0.999982
第 8 筆：0.000001
第 9 筆：0.000055
第 10 筆：0.000000


Step 9：決定 Classification Threshold

In [39]:
threshold = 0.5

y_pred = (y_prob >= threshold).astype(int)

print("Threshold:", threshold)
print("Prediction:", y_pred[:10])

Threshold: 0.5
Prediction: [0 1 0 1 0 1 1 0 0 0]


Step 10：建立 Confusion Matrix

In [40]:
# Step 10：建立 Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_val, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[41  1]
 [ 1 71]]


Step 11 : 計算accuracy,precision,recall,f1

In [41]:
# Step 11：計算四個分類指標

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

accuracy = accuracy_score(y_val, y_pred)
precision = precision_score(y_val, y_pred)
recall = recall_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

Accuracy : 0.9824561403508771
Precision: 0.9861111111111112
Recall   : 0.9861111111111112
F1-Score : 0.9861111111111112


Step 12：Threshold 微調

In [42]:
# Step 12：Threshold 微調

threshold = 0.7

y_pred_new = (y_prob >= threshold).astype(int)

# Confusion Matrix
cm_new = confusion_matrix(y_val, y_pred_new)

# 四個指標
accuracy_new = accuracy_score(y_val, y_pred_new)
precision_new = precision_score(y_val, y_pred_new)
recall_new = recall_score(y_val, y_pred_new)
f1_new = f1_score(y_val, y_pred_new)

print("Threshold:", threshold)
print()
print("Confusion Matrix:")
print(cm_new)
print()
print("Accuracy :", accuracy_new)
print("Precision:", precision_new)
print("Recall   :", recall_new)
print("F1-Score :", f1_new)

Threshold: 0.7

Confusion Matrix:
[[41  1]
 [ 5 67]]

Accuracy : 0.9473684210526315
Precision: 0.9852941176470589
Recall   : 0.9305555555555556
F1-Score : 0.9571428571428572


#進階

Step 13：建立第二個 Machine Learning Model

In [43]:
# Step 13：建立第二個 Machine Learning Model

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

Step 14：讓 Random Forest 預測 Validation Dataset

In [44]:
# Step 14：Random Forest 預測機率

rf_prob = rf_model.predict_proba(X_val_scaled)[:, 1]

print(rf_prob[:10])

[0.   1.   0.12 0.28 0.01 0.99 0.95 0.01 0.   0.  ]


Step 15：Random Forest 的 Threshold

In [45]:
threshold_rf = 0.5

rf_pred = (rf_prob >= threshold_rf).astype(int)

print("Threshold:", threshold_rf)
print("Prediction:", rf_pred[:10])

Threshold: 0.5
Prediction: [0 1 0 0 0 1 1 0 0 0]


Step 16：建立 Random Forest 的 Confusion Matrix

In [46]:
rf_cm = confusion_matrix(y_val, rf_pred)

print("Confusion Matrix:")
print(rf_cm)

Confusion Matrix:
[[39  3]
 [ 2 70]]


Step 17：計算 Random Forest 四個指標

In [47]:
rf_accuracy = accuracy_score(y_val, rf_pred)
rf_precision = precision_score(y_val, rf_pred)
rf_recall = recall_score(y_val, rf_pred)
rf_f1 = f1_score(y_val, rf_pred)

print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1-Score :", rf_f1)

Accuracy : 0.956140350877193
Precision: 0.958904109589041
Recall   : 0.9722222222222222
F1-Score : 0.9655172413793104


Step 18：Random Forest Threshold 微調

In [48]:
threshold_rf = 0.7

rf_pred_new = (rf_prob >= threshold_rf).astype(int)

rf_cm_new = confusion_matrix(y_val, rf_pred_new)

rf_accuracy_new = accuracy_score(y_val, rf_pred_new)
rf_precision_new = precision_score(y_val, rf_pred_new)
rf_recall_new = recall_score(y_val, rf_pred_new)
rf_f1_new = f1_score(y_val, rf_pred_new)

print("Threshold:", threshold_rf)
print()
print("Confusion Matrix:")
print(rf_cm_new)
print()
print("Accuracy :", rf_accuracy_new)
print("Precision:", rf_precision_new)
print("Recall   :", rf_recall_new)
print("F1-Score :", rf_f1_new)

Threshold: 0.7

Confusion Matrix:
[[42  0]
 [ 8 64]]

Accuracy : 0.9298245614035088
Precision: 1.0
Recall   : 0.8888888888888888
F1-Score : 0.9411764705882353
